import React, {Component} from 'react';

import {StyleSheet, Text, View, TextInput, FlatList, Picker, ScrollView, TouchableHighlight} from 'react-native';
import {Image as ReactImage} from 'react-native';


export default class QuestionnaireRate extends Component {


  render() {
    
    return (
    <ScrollView data-layer="d15a1800-0239-40e7-a56f-2833a3814a1e" style={styles.questionnaireWork1}>
        <View data-layer="3f1cfd75-186b-484d-a370-4080e896f879" style={styles.questionnaireWork1_divider}></View>
        <View data-layer="76eec166-fcfe-4958-b88d-20748f4f854d" style={styles.questionnaireWork1_header}>
            <View data-layer="fcadb115-532d-46c8-878f-0e600588d224" style={styles.questionnaireWork1_header_rectangle134}></View>
            <Text data-layer="b5404fcc-d117-47a4-8a5f-b2f68561cd1f" style={styles.questionnaireWork1_header_work}>Work</Text>
        </View>
        <Text data-layer="d90ff635-fa01-4d07-a1eb-9782d815e682" style={styles.questionnaireWork1_howBusyIsYourWorkSchedule}>How busy is your work schedule?</Text>

        <View data-layer="648fc6ad-7b4e-4e6e-9f8f-0ae5ecfd5765" style={styles.questionnaireWork1_continue34148045}>
            <View data-layer="e304000a-b159-43c4-9866-d7bb25ff2a19" style={styles.questionnaireWork1_continue34148045_rectangle132b4e471dd}></View>
            <Text data-layer="3d838d5b-9a46-45e8-85ee-11bd9c080975" style={styles.questionnaireWork1_continue34148045_x2}>2</Text>
        </View>
        <View data-layer="494d40d2-ad97-4ccd-8a9d-f3b27bafc987" style={styles.questionnaireWork1_continuee1852b56}>
            <View data-layer="400e3eeb-9335-4765-b426-14af25c13899" style={styles.questionnaireWork1_continuee1852b56_rectangle1320353854b}></View>
            <Text data-layer="f4083235-1b15-45f9-a739-93b8356f07aa" style={styles.questionnaireWork1_continuee1852b56_x3}>3</Text>
        </View>
        <View data-layer="65046789-75e3-4a38-8786-5149fe87b917" style={styles.questionnaireWork1_continue5a637f60}>
            <View data-layer="57fa9d36-c152-4074-aa2f-f585d516dcab" style={styles.questionnaireWork1_continue5a637f60_rectangle132d0cd8feb}></View>
            <Text data-layer="9ebebec4-c7c3-4262-8d7f-7b00afb52a40" style={styles.questionnaireWork1_continue5a637f60_x4}>4</Text>
        </View>
        <View data-layer="ecc9bc9d-7277-447b-a9b1-db883c122a2a" style={styles.questionnaireWork1_continue}>
            <View data-layer="65b5d56b-9702-4fb5-90aa-4be7d811f85f" style={styles.questionnaireWork1_continue_rectangle132}></View>
            <Text data-layer="100cdf10-03a9-43d8-af08-602b20e56a6d" style={styles.questionnaireWork1_continue_x5}>5</Text>
        </View>
        
    </ScrollView>
    );
  }
}

// QuestionnaireWork1.propTypes = {

// }

// QuestionnaireWork1.defaultProps = {

// }


const styles = StyleSheet.create({
  "questionnaireWork1": {
    "opacity": 1,
    "position": "relative",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 812,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_continuefb82f92b": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 295,
    "height": 48,
    "left": 40,
    "top": 459
  },
  "questionnaireWork1_continuefb82f92b_rectangle13238343ef4": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(38, 153, 251, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 24,
    "borderTopRightRadius": 24,
    "borderBottomLeftRadius": 24,
    "borderBottomRightRadius": 24,
    "width": 295,
    "height": 48,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_continuefb82f92b_x1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "lineHeight": 12,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 6,
    "height": 13,
    "left": 145,
    "top": 18.5
  },
  "questionnaireWork1_header14032a3d": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 169,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_header14032a3d_rectangle1340ece5e24": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(38, 153, 251, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 375,
    "height": 169,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_header14032a3d_adobeXd": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 30,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 156,
    "height": 33,
    "left": 110,
    "top": 112
  },
  "questionnaireWork1_divider": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(188, 224, 253, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 2,
    "borderTopRightRadius": 2,
    "borderBottomLeftRadius": 2,
    "borderBottomRightRadius": 2,
    "width": 295,
    "height": 4,
    "left": 40,
    "top": 402
  },
  "questionnaireWork1_header": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 375,
    "height": 169,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_header_rectangle134": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(38, 153, 251, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 375,
    "height": 169,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_header_work": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 30,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 70,
    "height": 33,
    "left": 153,
    "top": 112
  },
  "questionnaireWork1_howBusyIsYourWorkSchedule": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(38, 153, 251, 1)",
    "fontSize": 30,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 295,
    "height": 140,
    "left": 40,
    "top": 202
  },
  "questionnaireWork1_continue34148045": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 295,
    "height": 48,
    "left": 40,
    "top": 524
  },
  "questionnaireWork1_continue34148045_rectangle132b4e471dd": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(38, 153, 251, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 24,
    "borderTopRightRadius": 24,
    "borderBottomLeftRadius": 24,
    "borderBottomRightRadius": 24,
    "width": 295,
    "height": 48,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_continue34148045_x2": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "lineHeight": 12,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 6,
    "height": 13,
    "left": 145,
    "top": 18.5
  },
  "questionnaireWork1_continuee1852b56": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 295,
    "height": 48,
    "left": 40,
    "top": 594
  },
  "questionnaireWork1_continuee1852b56_rectangle1320353854b": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(38, 153, 251, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 24,
    "borderTopRightRadius": 24,
    "borderBottomLeftRadius": 24,
    "borderBottomRightRadius": 24,
    "width": 295,
    "height": 48,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_continuee1852b56_x3": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "lineHeight": 12,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 6,
    "height": 13,
    "left": 145,
    "top": 18.5
  },
  "questionnaireWork1_continue5a637f60": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 295,
    "height": 48,
    "left": 40,
    "top": 659
  },
  "questionnaireWork1_continue5a637f60_rectangle132d0cd8feb": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(38, 153, 251, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 24,
    "borderTopRightRadius": 24,
    "borderBottomLeftRadius": 24,
    "borderBottomRightRadius": 24,
    "width": 295,
    "height": 48,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_continue5a637f60_x4": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "lineHeight": 12,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 6,
    "height": 13,
    "left": 145,
    "top": 18.5
  },
  "questionnaireWork1_continue": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 295,
    "height": 48,
    "left": 40,
    "top": 724
  },
  "questionnaireWork1_continue_rectangle132": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(38, 153, 251, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopLeftRadius": 24,
    "borderTopRightRadius": 24,
    "borderBottomLeftRadius": 24,
    "borderBottomRightRadius": 24,
    "width": 295,
    "height": 48,
    "left": 0,
    "top": 0
  },
  "questionnaireWork1_continue_x5": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "lineHeight": 12,
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 6,
    "height": 13,
    "left": 145,
    "top": 18.5
  }
});